apiVersion: v1
kind: Service
metadata:
  labels:
    name: wordpress
  name: wordpress
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    name: wp
