apiVersion: v1
kind: Pod
metadata:
  labels:
    tier: fe
  name: wp-s
spec:
  containers:
  - image: wordpress
    name: wordpress
    ports:
    - containerPort: 80
    env:
    - name: WORDPRESS_DB_NAME
      value: wordpress
    - name: WORDPRESS_DB_USER
      value: wordpress
    - name: WORDPRESS_DB_PASSWORD
      value: wordpresspwd
    - name: WORDPRESS_DB_HOST
      value: mysql

